/**
 * BookForgePro - Comprehensive Book Creation Options
 * Generated with AI assistance for maximum user choice
 */

export const AUDIENCE_OPTIONS = [
  { label: "General readers", value: "general_readers" },
  { label: "CEOs and C-suite executives", value: "ceos_executives" },
  { label: "Entrepreneurs & startup founders", value: "entrepreneurs_founders" },
  { label: "Small business owners", value: "small_business_owners" },
  { label: "Managers & team leaders", value: "managers_team_leaders" },
  { label: "Employees & individual contributors", value: "employees_individuals" },
  { label: "Investors & venture capitalists", value: "investors_vcs" },
  { label: "Corporate trainers & L&D professionals", value: "trainers_lnd" },
  { label: "Consultants & coaches", value: "consultants_coaches" },
  { label: "Freelancers & solopreneurs", value: "freelancers_solopreneurs" },
  { label: "PhD students & researchers", value: "phd_students_researchers" },
  { label: "Undergraduate & college students", value: "undergrad_college_students" },
  { label: "High school students", value: "high_school_students" },
  { label: "Middle school students", value: "middle_school_students" },
  { label: "Teachers (K-12)", value: "teachers_k12" },
  { label: "University faculty & lecturers", value: "university_faculty" },
  { label: "Parents & caregivers", value: "parents_caregivers" },
  { label: "Expecting parents", value: "expecting_parents" },
  { label: "Children (ages 6-12)", value: "children_6_12" },
  { label: "Teens & young adults", value: "teens_young_adults" },
  { label: "Older adults & retirees", value: "older_adults_retirees" },
  { label: "Patients & healthcare consumers", value: "patients_healthcare_consumers" },
  { label: "Healthcare professionals (doctors, nurses, etc.)", value: "healthcare_professionals" },
  { label: "Mental health professionals & therapists", value: "mental_health_professionals" },
  { label: "Nonprofit leaders & volunteers", value: "nonprofit_leaders_volunteers" },
  { label: "Government & public sector professionals", value: "government_public_sector" },
  { label: "Policy makers & think tank staff", value: "policy_makers" },
  { label: "Engineers & technical professionals", value: "engineers_technical" },
  { label: "Software developers & IT professionals", value: "software_developers_it" },
  { label: "Scientists & lab researchers", value: "scientists_researchers" },
  { label: "Creative professionals (designers, artists)", value: "creative_professionals" },
  { label: "Writers & authors", value: "writers_authors" },
  { label: "Marketing & sales professionals", value: "marketing_sales_professionals" },
  { label: "HR & people operations professionals", value: "hr_people_ops" },
  { label: "Finance & accounting professionals", value: "finance_accounting_professionals" },
  { label: "Lawyers & legal professionals", value: "lawyers_legal_professionals" },
  { label: "Religious & spiritual leaders", value: "religious_spiritual_leaders" },
  { label: "Coaches (life, executive, performance)", value: "coaches_life_executive" },
  { label: "Hobbyists & enthusiasts", value: "hobbyists_enthusiasts" },
  { label: "Sports & fitness enthusiasts", value: "sports_fitness_enthusiasts" },
  { label: "Gamers & esports enthusiasts", value: "gamers_esports" },
  { label: "Writers of fiction", value: "fiction_writers" },
  { label: "Self-help & personal growth seekers", value: "self_help_personal_growth_seekers" },
  { label: "Career changers & job seekers", value: "career_changers_job_seekers" },
  { label: "Immigrants & international professionals", value: "immigrants_international_professionals" },
  { label: "Community organizers & activists", value: "community_organizers_activists" },
  { label: "Product managers & startup operators", value: "product_managers_startup_operators" },
  { label: "Online creators & influencers", value: "online_creators_influencers" }
];

export const WRITING_STYLES = [
  { label: "Academic research paper", value: "academic_research_paper" },
  { label: "Dissertation / thesis", value: "dissertation_thesis" },
  { label: "Textbook style", value: "textbook_style" },
  { label: "Scholarly monograph", value: "scholarly_monograph" },
  { label: "Literature review", value: "literature_review" },
  { label: "Technical report", value: "technical_report" },
  { label: "Lab manual / methods guide", value: "lab_manual_methods" },
  { label: "Case study (academic)", value: "case_study_academic" },
  { label: "White paper (business)", value: "white_paper_business" },
  { label: "Business report / briefing", value: "business_report_briefing" },
  { label: "Commercial / sales copy", value: "commercial_sales_copy" },
  { label: "Marketing / brand storytelling", value: "marketing_brand_storytelling" },
  { label: "Product guide / user manual", value: "product_guide_user_manual" },
  { label: "Consulting-style slide narrative", value: "consulting_slide_narrative" },
  { label: "Startup pitch deck narrative", value: "startup_pitch_narrative" },
  { label: "Business case study", value: "business_case_study" },
  { label: "Policy paper / policy brief", value: "policy_paper_brief" },
  { label: "Grant proposal style", value: "grant_proposal_style" },
  { label: "Instructional / how-to guide", value: "instructional_how_to" },
  { label: "Handbook / playbook", value: "handbook_playbook" },
  { label: "Training manual", value: "training_manual" },
  { label: "Journalistic (news feature)", value: "journalistic_news_feature" },
  { label: "Investigative journalism", value: "investigative_journalism" },
  { label: "Narrative non-fiction", value: "narrative_nonfiction" },
  { label: "Conversational / blog-style", value: "conversational_blog_style" },
  { label: "Storytelling (hero's journey)", value: "storytelling_heros_journey" },
  { label: "Memoir / personal narrative", value: "memoir_personal_narrative" },
  { label: "Self-help / motivational", value: "self_help_motivational" },
  { label: "Coaching / reflective journal", value: "coaching_reflective_journal" },
  { label: "Dialogue-driven", value: "dialogue_driven" },
  { label: "Fable / parable", value: "fable_parable" },
  { label: "Allegorical fiction", value: "allegorical_fiction" },
  { label: "Epic fantasy style", value: "epic_fantasy_style" },
  { label: "Science fiction style", value: "science_fiction_style" },
  { label: "Thriller / suspense style", value: "thriller_suspense_style" },
  { label: "Romance style", value: "romance_style" },
  { label: "Satirical / humorous", value: "satirical_humorous" },
  { label: "Minimalist (Hemingway-inspired)", value: "minimalist_hemingway" },
  { label: "Rich descriptive (Tolkien-inspired)", value: "rich_descriptive_tolkien" },
  { label: "Accessible analytical (Malcolm Gladwell-inspired)", value: "accessible_analytical_gladwell" },
  { label: "Marketing narrative (Seth Godin-inspired)", value: "marketing_narrative_seth_godin" },
  { label: "Character-driven literary (Jane Austen-inspired)", value: "character_driven_austen" },
  { label: "Psychological depth (Dostoevsky-inspired)", value: "psychological_depth_dostoevsky" },
  { label: "Magical realism (Gabriel García Márquez-inspired)", value: "magical_realism_marquez" },
  { label: "Stream of consciousness (Virginia Woolf-inspired)", value: "stream_of_consciousness_woolf" },
  { label: "Detective / mystery (Agatha Christie-inspired)", value: "detective_mystery_christie" },
  { label: "Speculative / idea-driven (Isaac Asimov-inspired)", value: "speculative_asimov" },
  { label: "Business narrative (Jim Collins-inspired)", value: "business_narrative_jim_collins" },
  { label: "Behavioral science storytelling (Daniel Kahneman-inspired)", value: "behavioral_science_kahneman" },
  { label: "Practical startup handbook (Eric Ries-inspired)", value: "startup_handbook_eric_ries" },
  { label: "Product / UX narrative (Marty Cagan-inspired)", value: "product_ux_marty_cagan" },
  { label: "Thought-leadership essay", value: "thought_leadership_essay" },
  { label: "Manifesto style", value: "manifesto_style" },
  { label: "Q&A / interview-based", value: "qa_interview_based" },
  { label: "Listicle / checklist driven", value: "listicle_checklist_driven" },
  { label: "Workbook with exercises", value: "workbook_with_exercises" },
  { label: "Devotional / daily readings", value: "devotional_daily_readings" },
  { label: "Script / screenplay style", value: "script_screenplay_style" }
];

export const BOOK_LENGTHS = [
  {
    label: "Short (5-7 chapters, 15K-25K words) – $9",
    value: "short",
    minChapters: 5,
    maxChapters: 7,
    minWords: 15000,
    maxWords: 25000,
    priceUSD: 9
  },
  {
    label: "Standard (8-12 chapters, 30K-50K words) – $19",
    value: "standard",
    minChapters: 8,
    maxChapters: 12,
    minWords: 30000,
    maxWords: 50000,
    priceUSD: 19
  },
  {
    label: "Comprehensive (15-20 chapters, 60K-80K words) – $79",
    value: "comprehensive",
    minChapters: 15,
    maxChapters: 20,
    minWords: 60000,
    maxWords: 80000,
    priceUSD: 79
  },
  {
    label: "Dissertation / Very long (20+ chapters, 80K+ words) – $199",
    value: "dissertation",
    minChapters: 20,
    maxChapters: null,
    minWords: 80000,
    maxWords: null,
    priceUSD: 199
  }
];

export const ILLUSTRATION_OPTIONS = [
  { label: "No illustrations (text only)", value: "none" },
  { label: "Simple icons & symbols", value: "icons_symbols" },
  { label: "Tables & structured layouts", value: "tables_structured_layouts" },
  { label: "Flowcharts & process diagrams", value: "flowcharts_process_diagrams" },
  { label: "Org charts & hierarchy diagrams", value: "org_charts_hierarchy" },
  { label: "Mind maps & concept maps", value: "mind_maps_concept_maps" },
  { label: "Graphs & data charts (bar, line, pie, etc.)", value: "graphs_data_charts" },
  { label: "Infographics & visual summaries", value: "infographics_visual_summaries" },
  { label: "Timelines & roadmaps", value: "timelines_roadmaps" },
  { label: "Frameworks & matrices (2x2, canvases, etc.)", value: "frameworks_matrices" },
  { label: "Wireframes & UI mockups", value: "wireframes_ui_mockups" },
  { label: "Technical diagrams (schematics, architectures)", value: "technical_diagrams" },
  { label: "Maps (geographical or conceptual)", value: "maps_geographical_conceptual" },
  { label: "Stock photos", value: "stock_photos" },
  { label: "Author-provided photos", value: "author_provided_photos" },
  { label: "Custom photography", value: "custom_photography" },
  { label: "Black & white line art", value: "black_white_line_art" },
  { label: "Full-color illustrations", value: "full_color_illustrations" },
  { label: "Character design / mascots", value: "character_design_mascots" },
  { label: "Comics & graphic novel panels", value: "comics_graphic_panels" },
  { label: "Children's book style art", value: "childrens_book_art" },
  { label: "Abstract decorative art", value: "abstract_decorative_art" },
  { label: "Hand-drawn sketches", value: "hand_drawn_sketches" },
  { label: "Watercolor-style art", value: "watercolor_style_art" },
  { label: "Collages & mixed media", value: "collages_mixed_media" },
  { label: "Calligraphy & decorative typography", value: "calligraphy_decorative_typography" },
  { label: "Pull quotes & callout boxes", value: "pull_quotes_callouts" },
  { label: "Chapter header illustrations", value: "chapter_header_illustrations" },
  { label: "Icons-only minimal visuals", value: "icons_only_minimal" },
  { label: "Full-page illustration plates", value: "full_page_plates" }
];
